language: c
branches:
  only:
  - master
addons: true
apt addons: true
cache components: true
compiler: gcc
before_install: true
install: true
before_script: true
jobs:
  include:
  - stage: build
    script:
    - echo "Hello world!"
    - python scripts/travis-ci.py send
    - python scripts/travis-ci.py build
    - python scripts/travis-ci.py deploy
    - python scripts/travis-ci.py test
before_cache: true
after_success: true
after_failure: true
before_deploy: true
deploy:
after_deploy: true
after_script: true