language: c
branches:
  only:
  - master
addons: true
apt addons: true
cache components: true
compiler: gcc
before_install: true
install: true
before_script: true
jobs:
  include:
  - stage: build
    script:
    - echo "Hello world!"
    - python scripts/test.py send
    - python scripts/test.py build
  - stage: deploy
    script:
    - python scripts/test.py deploy
  - stage: test
    script:
    - python scripts/test.py test
before_cache: true
after_success: true
after_failure: true
before_deploy: true
deploy: 
after_deploy: true
after_script: true
