language: c
branches:
  only:
  - master
addons:
  ssh_known_hosts: 115.182.224.11:8719
apt addons: true
cache components: true
compiler: gcc
before_install:
- openssl aes-256-cbc -K $encrypted_2359da2d74c7_key -iv $encrypted_2359da2d74c7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 115.182.224.11\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: true
before_script: true
jobs:
  include:
  - stage: build
    script:
    - scripts/travis-ci.sh build
  - stage: deploy
    script:
    - scripts/travis-ci.sh deploy
  - stage: test
    script:
    - scripts/travis-ci.sh test
before_cache: true
after_success: true
after_failure: true
before_deploy: true
deploy: 
after_deploy: true
after_script: true
